services:
  mysql:
    image: mysql:8.0
    container_name: farmacia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: farmacia_db
      MYSQL_USER: farmacia_user
      MYSQL_PASSWORD: farmacia_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/core/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - farmacia_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  api:
    build: .
    container_name: farmacia_api
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - farmacia_network
    environment:
      - DATABASE_URL=mysql+pymysql://farmacia_user:farmacia_pass@mysql:3306/farmacia_db

volumes:
  mysql_data:

networks:
  farmacia_network:
    driver: bridge