version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: farmacia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: farmacia_db
      MYSQL_USER: farmacia_user
      MYSQL_PASSWORD: farmacia_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/core/productos_init.mysql:/docker-entrypoint-initdb.d/productos_init.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - farmacia_network

  api:
    build: .
    container_name: farmacia_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - farmacia_network
    command: >
      sh -c "
        while ! nc -z mysql 3306; do
          echo 'Esperando MySQL...'
          sleep 2
        done
        echo 'MySQL está listo!'
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

volumes:
  mysql_data:

networks:
  farmacia_network:
    driver: bridge